heat_template_version: 2014-10-16

description: |
  Install a basic lamp stack on SUSE Openstack Cloud

parameters:
  key_name:
    type: string
    default: fschnizlein

  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
    default: m1.smaller

  image:
    type: string
    description: >
      Name or ID of the image to use for the LAMP server.
      The image must have the software config agents baked-in.

  private_net:
    type: string
    default: cd6f097c-f47b-419e-826f-41985d5d6783

  private_subnet:
    type: string
    default: foo

  public_net:
    type: string
    default: 958c0b51-d8d6-44e1-9f5e-6d9ee7b78854


resources:
  server_password:
    type: OS::Heat::RandomString

  lamp:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      admin_pass: { get_attr: [ server_password, value ] }
      flavor: { get_param: flavor }
      #software_config_transport: POLL_TEMP_URL
      #config_drive: true
      user_data_format: SOFTWARE_CONFIG
      networks:
        - port: { get_resource: lamp_port }

  lamp_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }

  lamp_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net }
      port_id: { get_resource: lamp_port }

# ---- ANSIBLE DEFINITIONS --------------------------------------
  nginx:
      type: OS::Heat::SoftwareConfig
      properties:
        group: script
        config: |
          #!/usr/bin/env bash
          touch /foo
        outputs:
          - name: result

  deploy_nginx:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: nginx
      server:
        get_resource: lamp

# ---- OUTPUTS --------------------------------------------------
outputs:
  server_password:
    description: Server Password
    value:
      get_attr: [ server_password, value ]
