---

- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /srv/www/htdocs/latest.tar.gz
    timeout: 60

- name: Unpack latest wordpress
  shell: tar xf /srv/www/htdocs/latest.tar.gz -C /srv/www/htdocs --strip-components=1
  args:
    warn: no

- name: Create wordpress configuration
  shell: cp /srv/www/htdocs/wp-config-sample.php /srv/www/htdocs/wp-config.php
  args:
    warn: no

- name: Configure wordpress database, username and password
  replace:
    dest: /srv/www/htdocs/wp-config.php
    regexp: "{{ item.then }}"
    replace: "{{ item.now }}"
    backup: no
  with_items:
    - { then: 'database_name_here', now: "{{ db.name }}" }
    - { then: 'username_here', now: "{{ db.user }}" }
    - { then: 'password_here', now: "{{ db.password }}" }
    - { then: 'localhost', now: "{{ hostvars[groups['database'][0]]['ansible_eth0']['ipv4']['address'] }}" }

