---
- name: Add http repository
  shell: zypper --non-interactive ar http://download.opensuse.org/repositories/server:/http/SLE_12/server:http.repo || true

- name: Refresh http repository
  shell: zypper --no-gpg-checks ref

- name: Install required packages
  zypper:
    name="{{ item }}"
    state=latest
  with_items:
    - nginx

- name: Check if vhosts.d exists
  file: path="/etc/nginx/vhosts.d" state=directory

- name: Setup nginx
  template: src=lamp.j2 dest=/etc/nginx/vhosts.d/lamp.conf owner=root

- name: Start nginx
  service: name=nginx enabled=true state=started

