#!/usr/bin/env bash

LAMP_ENV=${LAMP_ENV:-suse-cloud-de}

function validate_credentials() {
  unset OS_PASSWORD
  unset OS_USERNAME
  unset OS_TOKEN
  unset OS_AUTH_URL

  echo "OpenStack username: "
  read -r USERNAME_INPUT
  export USERNAME=${USERNAME_INPUT}

  echo "OpenStack password: "
  read -sr PASSWORD_INPUT
  export PASSWORD=${PASSWORD_INPUT}
}

start_lamp_stack() {
  echo "Starting lamp stack..."
  echo " :: ENV: ${LAMP_ENV}"
  ansible-playbook -e "action=start lamp_env=${LAMP_ENV} password=${PASSWORD} username=${USERNAME}" lamp_stack.yml
}

stop_lamp_stack() {
  echo "Stopping lamp stack..."
  echo " :: ENV: ${LAMP_ENV}"
  ansible-playbook -e "action=stop lamp_env=${LAMP_ENV} password=${OS_PASSWORD} username=${OS_USERNAME}" lamp_stack.yml
}


case $1 in
  start)
    validate_credentials
    start_lamp_stack
    ;;
  stop)
    validate_credentials
    stop_lamp_stack
    ;;
  *)
  echo "lamp_stack [start|stop]"
esac


