---

- name: Add php repository
  shell: zypper --non-interactive ar http://download.opensuse.org/repositories/devel:/languages:/php/SLE_12/devel:languages:php.repo || true

- name: Refresh php repository
  shell: zypper --no-gpg-checks ref

- name: Install required packages
  zypper:
    name="{{ item }}"
    state=latest
  with_items:
  - apache2
  - php5
  - php5-mysql
  - php5-gd
  - apache2-mod_php5

- name: Enable php5 apache module
  apache2_module: state=present name=php5

- name: Add index.php to DirectoryIndex
  lineinfile:
    dest: /etc/apache2/httpd.conf
    regexp: ^DirectoryIndex
    line: "DirectoryIndex index.html index.html.var index.php"

- name: Enable apache
  service: name=apache2 enabled=yes state=restarted

